const ACTIONS = {
  SET_SELECTED_STUDY_POPULATION_COHORT: 'setSelectedStudyPopulationCohort',
  SET_SELECTED_OUTCOME_COHORT: 'setSelectedOutcomeCohort',
  SET_DATASET_OBSERVATION_WINDOW: 'setDatasetObservationWindow',
  SET_DATASET_REMAINING_SIZE: 'setDatasetRemainingSize',
  SET_OUTCOME_OBSERVATION_WINDOW: 'setOutcomeObservationWindow',
  SET_MINIMUM_COVARIATE_OCCURRENCE: 'setMinimumCovariateOccurrence',
  SET_USE_ALL_COVARIATES: 'setUseAllCovariates',
  SET_NUMBER_OF_CROSS_VALIDATION_FOLDS: 'setNumberOfCrossValidationFolds',
  SET_PERCENTAGE_OF_DATA_TO_USE_AS_TEST: 'setPercentageOfDataToUseAsTest',
  DECREMENT_CURRENT_STEP: 'decrementCurrentStep',
  INCREMENT_CURRENT_STEP: 'incrementCurrentStep',
  SET_CURRENT_STEP: 'setCurrentStep',
  SET_OUTCOME: 'setOutcome',
  ADD_COVARIATE: 'addCovariate',
  DELETE_COVARIATE: 'deleteCovariate',
  UPDATE_MAF_THRESHOLD: 'updateMafThreshold',
  UPDATE_IMPUTATION_SCORE: 'updateImputationScore',
  UPDATE_NUM_PCS: 'updateNumPCs',
  UPDATE_SELECTED_HARE: 'updateSelectedHare',
  UPDATE_FINAL_POPULATION_SIZES: 'updateFinalPopulationSizes',
  SET_SELECTION_MODE: 'setSelectionMode',
  ADD_MESSAGE: 'addMessage',
  DELETE_MESSAGE: 'deleteMessage',
  SHOW_JOB_SUBMIT_MODAL: 'showJobSubmitModal',
  HIDE_JOB_SUBMIT_MODAL: 'hideJobSubmitModal',
  SET_JOB_NAME: 'setJobName',
  SET_SELECTED_MODEL: 'setSelectedModel',
  SET_SELECTED_MODEL_PARAMETERS: 'setSelectedModelParameters',
  SET_WORKFLOW_SUBMISSION_STATUS: 'setWorkflowSubmissionStatus',
};

export default ACTIONS;
