// @generated by tools/scanSitePaths.ts
// Do not edit manually. Edit src/middleware-impl.ts instead.
export { middleware } from './middleware-impl';

export const config = {
  matcher: [
  "/DataLibrary",
  "/Workspace",
  "/Profile"
],
};
