// @generated by tools/scanSitePaths.ts
// Do not edit manually. Edit src/proxy-impl.ts instead.
export { proxy } from './proxy-impl';

export const config = {
  matcher: [
  "/((?!_next/static|_next/image|_next/data|Login|api|403|404|no-workspace-access|favicon.ico|.*\\.ico$|.*\\.png$|.*\\.jpg$|.*\\.svg$|.*\\.json$).*)"
],
};
